### PR TITLE
Creating child login component 6

### LINKED ISSUE #6: Creating Child Login Component
- [x] Create Child Login Component
- [x] Renders a line stating what component is showing

### PR DESCRIPTION
**Pull request by Eteroa123**
# What I have done

Change the layout of the child login.
Added more images to represent different logins.

closes #6

### CODE REVIEW

**Review by mxbialostocki — COMMENTED** [review]
Morena Ete! Hope the south is good.

I can't actually see any changes to ChildLogin.jsx, can you pull from dev and then check that they are actually committed? I'm worried I might be doing something wrong.

We will probably need the Child Login component to get to mvp by the end of today so if it's possible that would be great.

Thank you!

**Comment by Eteroa123** [comment]
@mxbialostocki  Hey BamBam OMG no that fine !!!!! 
The changes that have been made was the images added !!!!!! ( Can you  see the new changes)
What else would like me to add!!!!!!!

**Comment by mxbialostocki** [comment]
Oh, I thought you'd updated the layout of the Child Login component!
Because we need these changes soon, are you okay with me leaning in on the ticket?

**Comment by Eteroa123** [comment]
@mxbialostocki  oh wow I misunderstood !!!! OMG yes please I would appreciate it !!!!! I actually based on the "desgin layout" . Hence why there are new images. Apologies BamBam

**Comment by mxbialostocki** [comment]
All good, will close this ticket and begin a new one. Will touch base with everyone when this is ready.

**Comment by Eteroa123** [comment]
@mxbialostocki  alright thank you!!! I will just leave the testing until the new version is done and I'll jump on the new ticket.

**Pull request merged**
